name: Deploy to production

on:
  repository_dispatch:
    types: deploy
  push:
    paths:
      - 'content/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZENDESK_USER: ${{ secrets.ZENDESK_USER }}
      ZENDESK_TOKEN: ${{ secrets.ZENDESK_TOKEN }}
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_INDEXER_KEY: ${{ secrets.ALGOLIA_INDEXER_KEY }}
      ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Deploy
        run: |
          cd _deploy
          go run *.go
