name: Linkinator

on: workflow_dispatch

jobs:
  linkinator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "content/**/*.md"
          skip: "^https://support.arduino.cc/hc, ^content.*/img/, http://arduino.local"
          markdown: true
